### ISSUE TITLE
[java]Feature/JH/갈등페이지 - (직접입력한 값) 프론트에서 넘겨준 json형태의 값을 DB에 저장(회은 완)

### ISSUE THREAD

**Issue by baejeonghyun23** [Team-A-I/otoo_java#13]
## 💡 Feature Issue

- 프론트에서 넘겨준 json형태의 값을 DB에 저장(직접입력한 값)
## 🌿  To-do

- [ ] service 클래스에 텍스트파일을 DB에 저장하는 로직 작성
- [ ] controller 클래스에 작성해둔 로직을 불러와 db저장 RestAPI 작성
- [ ] 프론트에서 파일업로드하면서 작성한 RestAPI가 호출되는지 확인
