### ISSUE TITLE
[java]Feature/SY/Admin페이지

### ISSUE THREAD

**Issue by catapracts** [Team-A-I/otoo_java#89]
## 💡 Feature Issue

- Admin페이지에서 사용할 함수 정의
## 🌿  To-do

- [ ] Banned여부에 따라 조회
- [ ] oAuthProvider 여부에 따라 조회
- [ ] Gender여부에 따라 조회
