### ISSUE TITLE
Feature/KH/자바JPA로 mysql연동 및 entity작성

### ISSUE THREAD

**Issue by heweun** [Team-A-I/otoo_java#9]
## 💡 Feature Issue

- 자바JPA로 mysql연동 및 entity작성
## 🌿  To-do

- [x] intellij mysql연동
- [x] User entity 작성
- [x] Files entity 작성
- [x] Result entity 작성
